### ISSUE TITLE
Switching from UnoCSS to TailwindCSS?

### ISSUE THREAD

**Issue by compilekaiten** [Nico-Mayer/vide#1]
Is it possible to swap from UnoCSS to TailwindCSS in this template?

**Comment by Nico-Mayer** [comment]
You could do it manually by uninstalling UnoCSS and removing UnoCSS from `vite.config main.ts `and install tailwind like so [Install Tailwind](https://tailwindcss.com/docs/guides/vite).

Then you would need to reconfigure Tailwind as example look at the `unocss.config.ts`.

**Comment by compilekaiten** [comment]
Easier than I expected. Got it working. Thanks!
